version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t scholzj/centos-builder-base:travis .
      - deploy:
          name: Login to Docker
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - deploy:
          name: Tag docker image
          command: docker tag scholzj/centos-builder-base:latest docker.io/scholzj/centos-builder-base:latest
      - deploy:
          name: Build Docker image
          command: docker push docker.io/scholzj/centos-builder-base:centos7-latest
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: docker-hub
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build:
          context: docker-hub
